repo_url: https://github.com/UnBIHC2025-1/IHC-2025.1-Grupo04
repo_name: IHC-2025.1-Grupo04

site_url: https://github.com/UnBIHC2025-1/IHC-2025.1-Grupo04
site_name: Check.Acess

use_directory_urls: False

nav:
  - Início - Check.Acess: 'index.md'

  - Desenvolvimento Web:
    - Desenvolvimento: 'devWeb/non_text_content.md'

  - Design:
    - Design: 'design/design.md'
  
  - Geração de Conteúdo:
    - Conteúdo: 'geracaoConteudo/conteudo.md'

  - Gestão de Projetos:
    - Gestão de Projetos: 'gestaoProjeto/gestaoProjeto.md'

  - Ferramentas:
    - Ferramentas de Acessibilidade: 'tools/ferramentas.md'

theme:
  name: readthedocs
  locale: pt_BR
  titles_only: true
  logo: imagens/logo.png
  favicon: imagens/logo.png

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: false
      clickable_checkbox: true

extra_css:
  - stylesheets/extra.css