repo_url: https://github.com/UnBIHC2025-1/IHC-2025.1-Grupo04
repo_name: IHC-2025.1-Grupo04

site_url: https://github.com/UnBIHC2025-1/IHC-2025.1-Grupo04
site_name: Check.Acess

use_directory_urls: False

nav:
  - Início - Check.Acess: 'index.md'

  - Desenvolvimento: 'devWeb/non_text_content.md'

  - Design: 'design/design.md'
  
  - Geração de Conteúdo: 'geracaoConteudo/conteudo.md'

  - Gestão de Projetos: 'gestaoProjeto/gestaoProjeto.md'

  - Ferramentas de Acessibilidade: 'tools/ferramentas.md'

theme:
  name: material
  locale: pt-BR
  titles_only: true
  logo: imagens/logo48.png
  favicon: imagens/logo48.png
  palette:
  #Dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: green
    accent: green
    toggle:
      icon: material/weather-night
      name: Modo escuro

  #White mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: green
    accent: green
    toggle:
      icon: material/weather-sunny
      name: Modo claro

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: false
      clickable_checkbox: true

extra_css:
  - stylesheets/extra.css
